[package]
name = "rust-cloud-discovery"
version = "0.1.0"
authors = ["sarowar <sarowar.cse@gmail.com>"]
edition = "2018"

[dependencies]
getset = "0.1"
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }